### ISSUE TITLE
App crashes when saving file on Android 7.1.2

### ISSUE THREAD

**Issue by vanitasvitae** [billthefarmer/editor#1]
Hi!
When I try to save a file, the app crashes with the following stacktrace:

```
07-24 21:51:22.040  3758  4418 D WifiStateMachine: updateCapabilities for config:FRITZ!Box 7362 SLfalse,false
07-24 21:51:22.100 19406 19406 D AndroidRuntime: Shutting down VM
07-24 21:51:22.104 19406 19406 E AndroidRuntime: FATAL EXCEPTION: main
07-24 21:51:22.104 19406 19406 E AndroidRuntime: Process: org.billthefarmer.editor, PID: 19406
07-24 21:51:22.104 19406 19406 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File java.io.File.getParentFile()' on a null object reference
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at org.billthefarmer.editor.Editor.write(Editor.java:290)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at org.billthefarmer.editor.Editor.saveFile(Editor.java:282)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at org.billthefarmer.editor.Editor.onOptionsItemSelected(Editor.java:171)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at android.app.Activity.onMenuItemSelected(Activity.java:3207)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1215)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:616)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:152)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at android.view.View.performClick(View.java:5637)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22429)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6124)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:882)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:74)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-24 21:51:22.104 19406 19406 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
07-24 21:51:22.106 19406 19406 E AndroidRuntime: Error reporting crash
07-24 21:51:22.106 19406 19406 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
07-24 21:51:22.106 19406 19406 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
07-24 21:51:22.106 19406 19406 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:615)
07-24 21:51:22.106 19406 19406 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5133)
07-24 21:51:22.106 19406 19406 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
07-24 21:51:22.106 19406 19406 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
07-24 21:51:22.106 19406 19406 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
07-24 21:51:22.106 19406 19406 I Process : Sending signal. PID: 19406 SIG: 9
07-24 21:51:22.177  3758  9479 D GraphicsStats: Buffer count: 11

```

Edit: The app also dies when I change the screen orientation (Probably for the same reason):

```
07-24 21:54:28.639 19662 19662 D AndroidRuntime: Shutting down VM
07-24 21:54:28.641 19662 19662 E AndroidRuntime: FATAL EXCEPTION: main
07-24 21:54:28.641 19662 19662 E AndroidRuntime: Process: org.billthefarmer.editor, PID: 19662
07-24 21:54:28.641 19662 19662 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.billthefarmer.editor/org.billthefarmer.editor.Editor}: java.lang.NullPointerException
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2667)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2728)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4521)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at android.app.ActivityThread.-wrap19(ActivityThread.java)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1485)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6124)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:882)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:74)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: Caused by: java.lang.NullPointerException
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at java.io.File.<init>(File.java:262)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at org.billthefarmer.editor.Editor.onCreate(Editor.java:90)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6682)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2620)
07-24 21:54:28.641 19662 19662 E AndroidRuntime: 	... 12 more
07-24 21:54:28.642 19662 19662 E AndroidRuntime: Error reporting crash
07-24 21:54:28.642 19662 19662 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
07-24 21:54:28.642 19662 19662 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
07-24 21:54:28.642 19662 19662 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:615)
07-24 21:54:28.642 19662 19662 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5133)
07-24 21:54:28.642 19662 19662 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
07-24 21:54:28.642 19662 19662 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
07-24 21:54:28.642 19662 19662 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
07-24 21:54:28.643 19662 19662 I Process : Sending signal. PID: 19662 SIG: 9
07-24 21:54:28.687  3758  9485 D GraphicsStats: Buffer count: 11
07-24 21:54:28.687  3758 12176 I ActivityManager: Process org.billthefarmer.editor (pid 19662) has died
```

**Comment by billthefarmer** [comment]
The next version will create a new file if the user saves text with no open file.
