### ISSUE TITLE
Window leak in  org.billthefarmer.editor.Editor  Activity.

### ISSUE THREAD

**Issue by YYYSSSHHH** [billthefarmer/editor#147]
**The stack trace:**  

[ 08-04 15:05:03.891  9052: 9052 E/WindowManager ]
android.view.WindowLeaked: Activity org.billthefarmer.editor.Editor has leaked window com.android.internal.policy.PhoneWindow$DecorView{902ce4e V.E...... R....... 0,0-575,353} that was originally added here
	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
	at android.app.Dialog.show(Dialog.java:319)
	at org.billthefarmer.editor.Editor.saveAsDialog(Editor.java:1411)
	at org.billthefarmer.editor.Editor.saveAs(Editor.java:1346)
	at org.billthefarmer.editor.Editor.onOptionsItemSelected(Editor.java:971)
	at android.app.Activity.onMenuItemSelected(Activity.java:2926)
	at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1151)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
	at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:200)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
	at android.widget.AbsListView$3.run(AbsListView.java:3903)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

[ 08-04 15:07:38.450  9052: 9052 E/WindowManager ]
android.view.WindowLeaked: Activity org.billthefarmer.editor.Editor has leaked window android.widget.PopupWindow$PopupDecorView{8b5c12e V.E...... ......ID 0,0-294,144} that was originally added here
	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1258)
	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1110)
	at android.widget.ListPopupWindow.show(ListPopupWindow.java:658)
	at com.android.internal.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:170)
	at com.android.internal.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:124)
	at android.widget.ActionMenuPresenter.onSubMenuSelected(ActionMenuPresenter.java:510)
	at com.android.internal.view.menu.MenuBuilder.dispatchSubMenuSelected(MenuBuilder.java:279)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:922)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
	at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:200)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
	at android.widget.AbsListView$3.run(AbsListView.java:3903)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

[ 08-04 15:14:21.289  9052: 9052 E/WindowManager ]
android.view.WindowLeaked: Activity org.billthefarmer.editor.Editor has leaked window com.android.internal.policy.PhoneWindow$DecorView{74f14ae V.E...... R....... 0,0-720,552} that was originally added here
	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
	at android.app.Dialog.show(Dialog.java:319)
	at org.billthefarmer.editor.Editor.openDialog(Editor.java:1823)
	at org.billthefarmer.editor.Editor.getFile(Editor.java:1727)
	at org.billthefarmer.editor.Editor.getFile(Editor.java:1710)
	at org.billthefarmer.editor.Editor.openFile(Editor.java:1688)
	at org.billthefarmer.editor.Editor.onOptionsItemSelected(Editor.java:965)
	at android.app.Activity.onMenuItemSelected(Activity.java:2926)
	at com.android.internal.policy.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1151)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
	at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:200)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
	at android.widget.AbsListView$3.run(AbsListView.java:3903)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Environment Info：**
APK Version: 1.61 (161) 

**Maybe can be solved with reference to this:** https://stackoverflow.com/questions/2850573/activity-has-leaked-window-that-was-originally-added
Do you confirm this bug?   Thank you.

**Comment by billthefarmer** [comment]
Issues with no information as to how they were obtained will be ignored and closed
