### ISSUE TITLE
Crash when opening text file

### ISSUE THREAD

**Issue by Thewisem** [billthefarmer/editor#153]
FATAL EXCEPTION: main
Process: org.billthefarmer.editor, PID: 6216
java.lang.OutOfMemoryError: Failed to allocate a 13833634 byte allocation with 1353424 free bytes and 1321KB until OOM
	at android.text.SpannableStringBuilder.toString(SpannableStringBuilder.java:1167)
	at android.text.TextUtils.writeToParcel(TextUtils.java:633)
	at android.widget.TextView$SavedState.writeToParcel(TextView.java:12157)
	at android.os.Parcel.writeParcelable(Parcel.java:1506)
	at android.os.Parcel.writeValue(Parcel.java:1412)
	at android.os.Parcel.writeSparseArray(Parcel.java:862)
	at android.os.Parcel.writeValue(Parcel.java:1437)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:734)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
	at android.os.Bundle.writeToParcel(Bundle.java:1157)
	at android.os.Parcel.writeBundle(Parcel.java:774)
	at android.os.Parcel.writeValue(Parcel.java:1403)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:734)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
	at android.os.Bundle.writeToParcel(Bundle.java:1157)
	at android.os.Parcel.writeBundle(Parcel.java:774)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:4203)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4230)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Comment by billthefarmer** [comment]
It looks like you loaded a large file and then either rotated the device or did something else to cause the app to attempt to save state. The built in file chooser has a size limit, I had left a size limit off files loaded in other ways if users insist on attempting to load large files. I have now put a limit in which will be in the next version.

**Comment by Thewisem** [comment]
Why are you limiting the size of file to open?

**Comment by Thewisem** [comment]
Isn't that counter productive

**Comment by billthefarmer** [comment]
Either I let users load huge files, break the app, and report issues on here, or I limit the file size and have users report issues (https://github.com/billthefarmer/editor/issues/89#issuecomment-544132202) on here.

**Comment by Thewisem** [comment]
Hmmm, why don't you check out other editors to see how they fixed the issue

**Comment by Thewisem** [comment]
The app simple notepad was able to open it no problem. Its free and open source and is on github

**Comment by billthefarmer** [comment]
This file needed nearly 14Mb of memory for the app to save state. Why do you think a simple editor intended for editing config files, etc, not writing a thesis, should be able to deal with something that size?
```
 java.lang.OutOfMemoryError: Failed to allocate a 13833634 byte allocation with 1353424 free bytes and 1321KB until OOM
```

**Comment by Ygarr** [comment]
> Hmmm, why don't you check out other editors to see how they fixed the issue

They can have another architecture

**Comment by Ygarr** [comment]
> The app notepad by braden farmer on fdroid was able to open it no problem. Its free and open source and is on github

Just tested it. Unusable for me. No search, hanging, renaming... much worse.
