### ISSUE TITLE
Error when open from Downloads

### ISSUE THREAD

**Issue by RamazanM** [billthefarmer/editor#61]
When i tried open a txt file from Downloads i got that error;

> 2018-10-26 03:51:43.821 24085-24085/org.billthefarmer.editor E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.billthefarmer.editor, PID: 24085
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/raw:/storage/emulated/0/Download/TDOdev1/AbstractFactory/AhsapOyuncak.txt flg=0x1 }} to activity {org.billthefarmer.editor/org.billthefarmer.editor.Editor}: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/TDOdev1/AbstractFactory/AhsapOyuncak.txt"
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4489)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4532)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/TDOdev1/AbstractFactory/AhsapOyuncak.txt"
        at java.lang.Long.parseLong(Long.java:590)
        at java.lang.Long.valueOf(Long.java:804)
        at org.billthefarmer.editor.FileUtils.getPath(FileUtils.java:425)
        at org.billthefarmer.editor.Editor.resolveContent(Editor.java:1170)
        at org.billthefarmer.editor.Editor.readFile(Editor.java:1133)
        at org.billthefarmer.editor.Editor.onActivityResult(Editor.java:657)
        at android.app.Activity.dispatchActivityResult(Activity.java:7548)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4485)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4532) 
        at android.app.ActivityThread.-wrap20(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by billthefarmer** [comment]
Ok, I have incorporated a variant of your fix. It will be in the next version.
